aws_region              = "us-east-1"
environment             = "dev"
project_name            = "HUG-Terraform-Challenge-Week2"
vpc_cidr                = "10.0.0.0/16"
availability_zones      = ["us-east-1a", "us-east-1b"]
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.11.0/24", "10.0.12.0/24"]
enable_nat_gateway      = true
single_nat_gateway      = true
enable_dns_support      = true
enable_dns_hostnames    = true
enable_alb              = true
instance_type           = "t2.micro"
instance_count          = 2
key_name                = ""
full_name               = "Abdel-Hamed Abdel-Nasser"
ingress_ports           = [22, 80, 443]
load_balancer_type      = "application"
tags                    = {}
