aws_region         = "us-east-1"
project_name       = "HUG-Lagos-Ibadan-Terraform-Challenge"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
availability_zone  = "us-east-1a"
instance_type      = "t2.micro"
key_name           = ""
full_name          = "Abdel-Hamed Abdel-Nasser"
ingress_ports      = [22, 80]
